name: evaporated_storage_example
description: todo
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.2
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_ui_auth: ^1.4.2
  firebase_ui_oauth_google: ^1.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  evaporated_storage:
    path: ..
  very_good_analysis: ^4.0.0+1
  cloud_firestore: ^4.8.1
  equatable: ^2.0.5
