name: fire_bloc
description:
  Extension to bloc which automatically persists and
  restores bloc and cubit states locally and remotely.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.4.3
  collection: ^1.18.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5
  meta: ^1.15.0
  very_good_analysis: ^6.0.0

dev_dependencies:
  test: ^1.25.7
