name: fire_bloc
description: todo
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.1
  collection: ^1.17.1
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.1
  meta: ^1.9.1
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  test: ^1.21.6
