name: hydrated_bloc_firebase_storage
description: todo
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.3
